config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :units
  get 'landing/index'
  root 'landing#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/unit.rb
class Unit < ApplicationRecord
    
    belongs_to :user
    
    before_create do
        self.members = 1 if members.nil?
    end
    
    after_create do
        @user = self.user_id
        self.owner = User.find(@user).email
    end
    
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :units
         
  validates :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/landing_controller.rb
class LandingController < ApplicationController
  def index
  end
end

app/controllers/units_controller.rb
class UnitsController < ApplicationController

  def index
    @units = Unit.all
  end

  def show
    @unit = Unit.find(params[:id])
    @user = User.find(@unit.user_id)
  end
  
  def new
    @unit = Unit.new
  end

  def create
    @user = current_user
    @unit = @user.units.create(unit_params.merge(owner: @user.email))
    
    redirect_to units_path
  end
  
  def edit
    @unit = Unit.find(params[:id])
  end

  def update
    @unit = Unit.find(params[:id])
    @unit.update(unit_params)

    redirect_to unit_path(@unit)
  end
  
  def destroy
    @unit = Unit.find(params[:id])
    @unit.destroy
      
    redirect_to units_path
    
  end

  private

  def unit_params
    params.require(:unit).permit(:unit_name, :owner, :members)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper


end

app/helpers/landing_helper.rb
module LandingHelper

end

app/helpers/units_helper.rb
module UnitsHelper
end

app/views/landing/index.html.erb
<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-4">High Quality Mission Builder</h1>
    <p class="lead">Create ConOps, Concept of Fires and GRGs on the fly!</p>
  </div>
</div>

app/views/layouts/_flash.html.erb
<div class="flash">
  <% if flash[:notice] %>
    <div class="alert alert-success">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash[:notice] %>
    </div>
  <% elsif flash.now[:alert] %>
    <div class="alert alert-danger">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash.now[:alert] %>
    </div>
  <% elsif flash[:alert] %>
    <div class="alert alert-warning">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash[:alert] %>
    </div>
  <% end %>
</div>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <%= link_to "Mase Support Builder", root_path, :class => 'navbar-brand' %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">

    <% if user_signed_in? %>
      <li><%= link_to current_user.email, edit_user_registration_path, :class => 'navbar-link' %></li>
      <li><%= link_to "Units", units_path, :class => 'navbar-link' %></li>
      <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link' %></li>
    <% else %>
      <li><%= link_to "Signup", new_user_registration_path, class: 'navbar-link' %></li>
      <li><%= link_to "Signin", new_user_session_path, class: 'navbar-link' %></li>
    <% end %>

    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mase</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: "layouts/nav" %>
    <%= render partial: 'layouts/flash' %>

    <%= yield %>
  </body>
</html>

app/views/units/_form.html.erb
<%= form_with model: @unit do |form| %>
  <%= form.text_field :unit_name, placeholder: "Unit Name" %>

  <%= form.submit %>
<% end %>

app/views/units/edit.html.erb
<h3>Edit Unit</h3>

<%= render partial: "form.html.erb" %>

app/views/units/index.html.erb
<h1><%= current_user.username ? current_user.username : current_user.email %> </h1>

<h4>Your Units</h4>
<ul>
  <% @units.each do |unit| %>
    <li><%= link_to unit.unit_name, unit_path(unit)  %></li>
  <% end %>
</ul>

<small><%= link_to "Create new Unit", new_unit_path %></small>

app/views/units/new.html.erb
<h3>Create a Unit</h3>

<%= render partial: "form.html.erb" %>

app/views/units/show.html.erb
<h3>Unit: <%= @unit.unit_name %></h3>
<h4>Owner: <%= @user.username %></h4>
<h4>Members: <%= @unit.members %></h4>

<h2>Missions</h2>
<ul>
    <li>M2 Snakebite</li>
    <li>M4 Sandflats</li>
</ul>

<% if current_user.id == @unit.user_id %>
    <small><%= link_to "Add Member", units_path %></small></br>
    <small><%= link_to "Edit Unit", edit_unit_path(@unit) %></small></br>
    <small><%= link_to "Delete Unit", @unit, method: :delete, data: {confirm: "Are you sure?"} %></small>
<% end %>